### PR TITLE
fix variable and string typos in example site

### PR DESCRIPTION
**Pull request by efigi**
I used this theme for my blog, and it's really good! I just noticed the typos in the example site (which I used as the template) so I just fixed them.

### CODE REVIEW

**Comment by kucw** [comment]
Hi @efigi, Google Analytics crashes after you fix the typos at line 87 "googleAnalyticsID". Could you please help to change it back? Thank you!

**Comment by efigi** [comment]
> Hi @efigi, Google Analytics crashes after you fix the typos at line 87 "googleAnalyticsID". Could you please help to change it back? Thank you!

Oh okay! I'll send another PR then. So it worked for you before my typo fix?

**Comment by kucw** [comment]
Thanks for your quick reply. And yes, it works well before this PR been merged on my end.

**Comment by efigi** [comment]
Okay! I sent a PR for it

**Pull request merged**
